### ISSUE TITLE
Debugging excessive import times?

### ISSUE THREAD

**Issue by elfprince13** [cuddlyogre/ExportLDraw#37] opened 2023-05-15 21:20 UTC
Hi! I have a large (1.8MB) file that seems to hang the importer. Killed my most recent attempt after waiting for 2.5 hours. Can you suggest a workflow for attaching a Python debugger and stepping into see if I can isolate where in the code things are going wrong? Memory usage seems totally reasonable.

**Comment by cuddlyogre** [comment] 2023-05-15 21:55
Usually this happens on models that have a massive amount of parts and what appears to be hanging is just the system processing successfully, but quietly. I don't have print statements because it slows things down, on Windows at least. 

If you open the console window before import, you can ctrl-c to kill the import, and usually the editor window will show the parts that have imported up to that point. 

There is a profile function that you can use that will create a file in your home directory that snakeviz can open, but I don't know if it works if you kill the import early. 

Are you willing to attach the file? I have other tools I've built for my own purposes that can help figure out where the problem is.

**Comment by elfprince13** [comment] 2023-05-16 00:38
I thought part of the problem might be that I had a lot of `lsynth`-generated parts, but importing the unprocessed file with just the constraints didn't seem to help either. I do also have some custom-patterned parts with raw primitives in my MPD, not sure if that's a failure case as well. I can share the file via Google Drive, if that works?

**Comment by cuddlyogre** [comment] 2023-05-16 01:07
That will work.

**Comment by elfprince13** [comment] 2023-05-16 01:53
Great, thanks! You should have just gotten an email with the shared files. If you're benchmarking ~13s import on the UCS Star Destroyer and this import takes multiple hours, even accounting for differences in hardware (I'm on a 2013 Macbook Pro), it seems like some algorithm or data-structure has super-linear complexity, and I'm definitely happy to help debug/rework that, but not super familiar with this code yet.

**Comment by cuddlyogre** [comment] 2023-05-16 02:32
I found an error in my header parsing logic. I've fixed the bug. Your model now loads no problem. Very cool by the way.

I'm about to create a new release, but before I do, I'd like to add proper lsynth support. 

According to http://www.holly-wood.it/lsynth/tutorial-en.html, the lsynth parts should be in ldraw_root/Unofficial/parts. Is yours set up like that or is it normal to have a separate lsynth part directory? I am unfamiliar with the usage of lsynth.

**Comment by elfprince13** [comment] 2023-05-16 13:37
Thanks! And yeah, all my lsynth parts (constraints, and the segments for the final synthesized parts) are in `Unofficial/parts`. 

Honestly, what would be amazing is reimplementing the lsynth behavior in terms of native Blender primitives (repeating mesh along spline/curve), so that I could run soft-body physics sims on top for doing animations / or just reposing flexible elements in Blender after import.

**Comment by cuddlyogre** [comment] 2023-05-17 09:23
I've created a new release that includes a fix for this issue. Please let me know if you have any more problems.

https://github.com/cuddlyogre/ExportLDraw/releases/tag/2023-05-17-00

**Comment by elfprince13** [comment] 2023-05-17 19:43
awesome, thank you!

**Comment by elfprince13** [comment] 2023-05-23 20:32
Just wanted to come back and say thanks again! My model is [up on Lego Ideas](https://ideas.lego.com/projects/0b565e40-80a4-46bb-bf10-9bbcc26b40e5) now, and this was the last piece, metaphorically speaking.

**Comment by cuddlyogre** [comment] 2023-05-23 21:13
Nice! Those renders look fantastic! I hope your set gets accepted. It's very cool.

**Closed as completed** 2023-08-20 02:14 UTC
