### ISSUE TITLE
Blender crash on undo

### ISSUE THREAD

**Issue by AlexFundorin** [cuddlyogre/ExportLDraw#18] opened 2021-06-06 21:27 UTC
Blender 3.0.0
Once I import an .ldr file, while, obviously, forgetting to select a proper preset (set path to ldraw lib), I get a couple of empty folder.
So, I'm pressing ctrl-z to undo the last step. This is where Blender crushes for me, every time.

**Comment by cuddlyogre** [comment] 2021-06-07 03:27
I've merged the fix into master. Update the plugin and undo will now work.

**Comment by AlexFundorin** [comment] 2021-06-07 12:46
Sadly, the latest master just broke the functionality all together. https://i.imgur.com/nOcBSw9.png

**Comment by AlexFundorin** [comment] 2021-06-07 16:55
I can't even enable the last version of the addon in Blender. The main checkbox doesn't allow me to click it.

**Comment by cuddlyogre** [comment] 2021-06-07 18:05
The error was caused by a non existent import that I've now fixed and verified as working on a couple machines. Please update again and it should work.

**Comment by AlexFundorin** [comment] 2021-06-07 18:16
I was able to activate the latest version. It took about a minute to import Blizzard Baron model from Ice Planet 2002. Hi-res import settings. Took about 10 seconds for the same set in the previous working version.
Adding an initial HDRI to the scene with an imported set is also taking about 20-30 seconds now. Was 2-3 seconds. 
Switching HDRI's afterwards is going as fast as before.
But, the addon is working now, at least. So, thank you, dear Ogre.

**Comment by cuddlyogre** [comment] 2021-06-07 18:25
Do you have a link to the file so I can test? I haven't tested on 3.0 so I don't know if the speed changes are due to my work or a change in Blender.

**Comment by AlexFundorin** [comment] 2021-06-07 18:27
Sure. https://www.dropbox.com/s/7a9kmw239dnaah9/6879-1%20-%20Blizzard%20Baron.mpd?dl=0

**Comment by cuddlyogre** [comment] 2021-06-07 18:35
![image](https://user-images.githubusercontent.com/3506795/121070861-d6eee600-c794-11eb-8d75-0b17ff36198b.png)

It may be a 3.0 thing. I'm able to get about 3 seconds for standard and 4 seconds for high res. I'll have to test with that to see where it's slowing down.

**Comment by AlexFundorin** [comment] 2021-06-07 18:38
Updated Blender to the latest version an now everything's as it was before. We can close the issue now, I guess.

**Comment by cuddlyogre** [comment] 2021-06-07 18:41
Fantastic. I hope you enjoy the addon!

**Closed as completed by cuddlyogre** 2021-06-07 18:41 UTC
